### ISSUE TITLE
Error Testing Notification callback

### ISSUE THREAD

**Issue by agung-wete** [veritrans/SNAP-Woocommerce#6]
While testing [Test notification callback](https://dashboard.sandbox.midtrans.com/settings/vtweb_configuration/test_callback), got this:

> [STDERR] PHP Warning: Illegal string offset 'transaction_id' in /var/www/vhosts/XXX/wp-content/plugins/midtrans-woocommerce/lib/veritrans/Veritrans/Notification.php on line 20
> 
>  [STDERR] PHP Fatal error: Uncaught Exception: Veritrans Error (404): Transaction doesnt exist. in /var/www/vhosts/XXXXX/wp-content/plugins/midtrans-woocommerce/lib/veritrans/Veritrans/ApiRequestor.php:96

Using ver 2.4.5

**Comment by agung-wete** [comment]
https://github.com/veritrans/SNAP-Woocommerce/blob/717bd19d16a931f3b8210545dd59a44d92434d20/lib/veritrans/Veritrans/Notification.php#L19-L21

Line 20,  `$raw_notification->transaction_id` ?

**Comment by agung-wete** [comment]
Got something:

```php
$raw_notification = json_decode(file_get_contents($input_source), true);	
// error_log('TIPE:'.gettype($raw_notification) ); //result is "string" not array
```

**Comment by rizdaprasetya** [comment]
Hi @agung-wete 
Thanks for contacting.

Unfortunately for now the `Test notification callback` is in incorrect format. So please ignore the error caused by it.
For testing with Woocommerce, we recommend you to do transaction in your Woocommerce site using Midtrans Gateway which set to use sandbox environment, your server will receive correct `notification callback` using this method.

Thanks.

**Comment by agung-wete** [comment]
ya, kami berhasil test dengan mode sandbox, tapi kami harus ubah :
```
$raw_notification = json_decode(file_get_contents($input_source), true);	
// error_log('TIPE:'.gettype($raw_notification) ); //result is "string" not array

//need to decode again
$raw_notification = json_decode($raw_notification, true);
```

PHP ver 7.1,  plugin ver 2.4.5
