### ISSUE TITLE
Plugin conflict and unable to load Jquery

### ISSUE THREAD

**Issue by gusleo** [veritrans/SNAP-Woocommerce#63]
Sometimes the plugin conflict with other plugin, makes midtrans-payment-page-main.js unable to load jQuery because this js script load before Jquery load.
![Screenshot_227](https://user-images.githubusercontent.com/15825376/131526080-609d51ef-8276-4443-a3e8-103e36749005.png)

**Comment by rizdaprasetya** [comment]
Hi @gusleo thanks for letting us know your specific issue that you find. And thanks for the [PR that tries to solve the issue](https://github.com/veritrans/SNAP-Woocommerce/pull/64) 👍 .
However, the simpler solution is to remove the JQuery all together from our script, because it actually is not used. It was there because of JS template from WP guide. 

It is now solved on v2.31.1 we just released today. Please try to update and let us know if you still get the issue.

Also can you let us know, what plugin that cause this jQuery to be loaded late? Or if you don't know which plugin, you can list all your active plugins.
My guess is it is likely an asset optimizer plugin, which sometimes can change the order of when JS asset load.

Thanks again for your contribution by reporting to us, definitely will prevent someone else from encountering the issue 🙂
